In [ ]:
pip install nnfs

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

class Layer_Dense:
  def __init__(self,n_inputs,n_neurons):
      self.weights = 0.01 * np.random.randn(n_inputs,n_neurons)
      self.biases = np.zeros((1,n_neurons))

  def forward(self,inputs):
      self.outputs = np.dot(inputs, self.weights) + self.biases

class Activation_ReLu:
  def forward(self,inputs):
      self.outputs = np.maximum(0,inputs)


class Activation_SoftMax:
  def forward(self,inputs):
      exp_Values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
      probabilities =  exp_Values / np.sum(exp_Values, axis = 1, keepdims = True)
      self.outputs = probabilities

x,y = spiral_data(samples = 100, classes = 3)
Dense1 = Layer_Dense(2,3)
AvtivationReLu = Activation_ReLu()
Dense2 = Layer_Dense(3,3)
ActivationSoftMax = Activation_SoftMax()



Dense1.forward(x)
AvtivationReLu.forward(Dense1.outputs)

Dense2.forward(AvtivationReLu.outputs)

ActivationSoftMax.forward(Dense2.outputs)


ActivationSoftMax.outputs[:100]


array([[0.33333334, 0.33333334, 0.33333334],
       [0.3333332 , 0.3333332 , 0.33333364],
       [0.3333329 , 0.33333293, 0.3333342 ],
       [0.3333326 , 0.33333263, 0.33333477],
       [0.33333233, 0.3333324 , 0.33333528],
       [0.33333284, 0.33333287, 0.3333343 ],
       [0.33333182, 0.3333319 , 0.33333626],
       [0.3333318 , 0.3333319 , 0.33333623],
       [0.3333315 , 0.3333316 , 0.33333692],
       [0.33333105, 0.3333312 , 0.33333772],
       [0.3333308 , 0.33333096, 0.3333382 ],
       [0.3333311 , 0.33333126, 0.33333766],
       [0.33333054, 0.3333307 , 0.33333877],
       [0.3333301 , 0.3333303 , 0.3333396 ],
       [0.33333012, 0.33333036, 0.33333954],
       [0.33332998, 0.3333302 , 0.3333398 ],
       [0.33333126, 0.33333188, 0.33333683],
       [0.33332938, 0.33332965, 0.33334094],
       [0.33332992, 0.33333033, 0.33333975],
       [0.33332875, 0.33332902, 0.33334222],
       [0.33332875, 0.33332902, 0.3333422 ],
       [0.33333096, 0.33333182, 0.3333372 ],
       [0.

In [ ]:
softmax_output = np.array([
    [0.7,0.1,0.2],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])

class_Target = [0,1,1]
print(softmax_output[[0,1,2], class_Target])

[0.7 0.5 0.9]


In [ ]:
print(-np.log(softmax_output[
    range(len(softmax_output)),class_Target
]))
neg_log = -np.log(softmax_output[
    range(len(softmax_output)),class_Target
])
average_Loss = np.mean(neg_log)
print(average_Loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


In [ ]:
y_true_check  = np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]
])

y_pred_clipped_check = np.array([
    [0.7,0.2,0.1],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])

A = y_pred_clipped_check*y_true_check
B = np.sum(A,axis = 1)
c = -np.log(B)
np.mean(c)

0.38506088005216804

In [ ]:
class Loss:
  def calculate(self,output,y):
    sample_losses = self.forward(output,y)
    data_loss = np.mean(sample_losses)
    return data_loss

In [ ]:
class Loss_CategoricalCrossEntropy(Loss):
  def forward(self,y_pred,y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred,1e-7,1-1e-7)
    if len(y_true.shape) == 1:
      correct_confidence = y_pred_clipped[
      range(samples),
      y_true]

    elif len(y_true.shape) ==2:
      correct_confidence = np.sum(
          y_pred_clipped*y_true,
          axis = 1
      )

    negative_log_likelihood = -np.log(correct_confidence)
    return negative_log_likelihood

In [ ]:
softmax_outputs = np.array([[0.7,0.1,0.2],
                            [0.1,0.5,0.4],
                            [0.02,0.9,0.08]])

class_Targets = np.array([[1,0,0],
                          [0,1,0],
                          [0,1,0]])

loss_Function = Loss_CategoricalCrossEntropy()
loss = loss_Function.calculate(softmax_outputs, class_Targets)
loss

0.38506088005216804

In [ ]:
import numpy as np
import nnfs

nnfs.init()

from nnfs.datasets import spiral_data

ModuleNotFoundError: No module named 'nnfs'